### PR TITLE
Support LZMA1+BCJ decompression, Deflate, BZip2 + BCJ compression/decompression

### LINKED ISSUE #178: decompression get wrong: no output data.
**Describe the bug**
decompression get wrong: no output data.

**To Reproduce**
1. run command in terminal："py7zr x 1593750358075c++obf7.7z"
2. See error: decompression get wrong: no output data.

**Environment:**
 - OS: Windows 10
 - Python 3.8
 - py7zr version: 0.7.4

**Test data(please attach in the report):**
The file url：http://qcw2817j7.bkt.gdipper.com/1593750358075c%2B%2Bobf7.7z
(No virus)

**Additional context**
1. When I use 7z client(https://www.7-zip.org) or winrar, I can correctly decompress this file.
2. I can use your library to decompress other .7z files I have.

Thank you~

### PR DESCRIPTION
**Pull request by miurahr**
- Introduce BCJ filter written by Python
- Hack to use alternative BCJ filter for LZMA1+BCJ decompression
- Add support Deflate+BCJ(X86) and Bzip2+BCJ(X86)
- Change ZStandard, and ZStandard+BCJ(X86)  to unsupported, because of  new test result become failure.
- Fixed #178 
- Make LZMA1 + BCJ(ARM, ARMT, Sparc, PPC, IA64) decompression unsupported because of lzma module raises exception.

### CODE REVIEW

**Comment by animalize** [comment]
Maybe `BCJEncoder` is not necessary. When compressing, the pipeline order:
1. x86 BCJ filter 
2. LZMA1 compress

The End Marker will not affect this process.
```
    /*
     * Buffer to hold a mix of filtered and unfiltered data. This
     * needs to be big enough to hold Alignment + 2 * Look-ahead:
     *
     * Type         Alignment   Look-ahead
     * x86              1           4
     * PowerPC          4           0
     * IA-64           16           0
     * ARM              4           0
     * ARM-Thumb        2           2
     * SPARC            4           0
     */
```
IMHO there should be a "ARM-Thumb alternative filter" for decompress as well, it would be nice to test all BCJ filters.

Don't know if it worthy to support BCJ2 in this way.

**Comment by miurahr** [comment]
> Maybe BCJEncoder is not necessary. 

BCJEncoder is used with ZStandard, Deflate and Bzip2 compressors, because lzma module's encoder only allows a combination with LZMA and LZMA2.

**Comment by miurahr** [comment]
There are already many tests for all kinds of BCJ filters, but there are passed well (unfortunately?).
Adding more tests.

**Comment by animalize** [comment]
It should test a native binaray executeable of ARM/SPARC/ARM/etc.
And make sure the filtered data has changed by the BCJ filter.

**Comment by miurahr** [comment]
> It should test a native binary executable of ARM/SPARC/etc.
> And make sure the filtered data has been changed by the BCJ filter.

Catch a good point. I'd like to drop nonsense tests. I'd like to raise new issue for it.

**Pull request merged**
