### PR TITLE
feat: 3.13 support

### PR DESCRIPTION
**Pull request by Ravencentric**
## Pull request type

- Build and release changes

## What does this PR change?

~~Currently nothing, I want the CI to pass with minimal changes before doing anything else~~ CI passed, so time for changes:
- [x] Drops [3.8](https://endoflife.date/python) and adds 3.13 to the test matrix
- [x] Update all the GitHub actions to their latest versions
- [x] Replace old style strings with f-strings
- [x] Replace `typing.List` (and similar) with their [standard equivalent](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)
- [x] Upgrade `aarch64` from `ubuntu20.04+py39` to `ubuntu22.04+py310`.
- [x] Remove code paths that checked for python versions less than `3.9`

### CODE REVIEW

**Comment by Ravencentric** [comment]
@miurahr do you have any idea why the tests are failing? I'm sort of lost here since I made minimal changes?

**Comment by miurahr** [comment]
> @miurahr do you have any idea why the tests are failing? I'm sort of lost here since I made minimal changes?

#611 fix the typo not only document but variable name. It enabled the previous dead code, which cause the behavior change, and raised the bug.

I remove the problematic line in previous master branch commit. Could you rebase the PR on the latest master?

**Comment by miurahr** [comment]
`uraimo/run-on-arch-action@v2` is failed

**Comment by Ravencentric** [comment]
> `uraimo/run-on-arch-action@v2` is failed

Yep, working on a fix right now

**Comment by Ravencentric** [comment]
@miurahr I think this PR is done and ready for review

**Review by miurahr — APPROVED** [review]

**Pull request merged**
