### PR TITLE
feat: add support for `mode="x"` in `py7zr.SevenZipFile()`

### PR DESCRIPTION
**Pull request by Ravencentric**
## Pull request type

- Feature enhancement

## Which ticket is resolved?

- https://github.com/miurahr/py7zr/issues/587

## What does this PR change?
- Add support for `mode="x"` in `py7zr.SevenZipFile()`

## Other information
N/A

### CODE REVIEW

**Comment by miurahr** [comment]
> check: commands[0]> flake8 py7zr tests
>   tests/test_basic.py:30:5: BLK100 Black would make changes.
>   tests/test_basic.py:30:9: E117 over-indented

Please fix the check error

**Comment by Ravencentric** [comment]
fixed

**Comment by miurahr** [comment]
In python zipfile manual,

> The mode parameter should be 'r' to read an existing file, 'w' to truncate and write a new file, 'a' to append to an existing file, or 'x' to exclusively create and write a new file. If mode is 'x' and file refers to an existing file, a [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) will be raised.

I think we need to raise `FileExistsError` if the file exists. I'd like to review for it.

**Comment by Ravencentric** [comment]
It does raise FileExistsError if the file already exists. It's in the rest case
[here](https://github.com/miurahr/py7zr/pull/588/files#diff-29093b485f46bc37dda5e0854cfc54e289f24e206207afb81dff1c527cb001a7R32)

**Comment by miurahr** [comment]
There is a test that check creation and also exception. LGTM.

**Comment by miurahr** [comment]
#647 report the bug.

**Pull request merged**
