### PR TITLE
Backport: Raise PasswordRequired when no password is given for encrypted archive

### PR DESCRIPTION
**Pull request by miurahr**
Backport #216

### CODE REVIEW

**Comment by robustTechie** [comment]
@miurahr for me it is not working isn't it deployed yet?

**Comment by miurahr** [comment]
released as v0.9.4 with the fix. Most recent version is v0.9.5.

**Comment by miurahr** [comment]
The test case, which try extraction of encrypted archive without password,  passed in v0.9.5 CI test.

Row log here

https://pipelines.actions.githubusercontent.com/AI5hAGx2GFYoD635nxSXpMv8obErKR6Fv9onjm5xiwhjRcAjZ1/_apis/pipelines/1/runs/1299/signedlogcontent/5?urlExpires=2020-08-29T09%3A57%3A41.7995732Z&urlSigningMethod=HMACV1&urlSignature=FKkfcUhdOq%2FvG7gOtTyuGw6hWRkKIaMr8ZDsrmsBXog%3D

```
2020-08-11T21:28:50.3628031Z tests/test_encryption.py::test_extract_encrypted_no_password PASSED      [ 32%]
2020-08-11T21:28:50.3944741Z tests/test_encryption.py::test_cli_encrypted_no_password PASSED          [ 33%]
```

**Comment by robustTechie** [comment]
> released as v0.9.4 with the fix. Most recent version is v0.9.5.

yeah I am having the same version, but if I enter wrong password or no password then it shows

`Password: 
Traceback (most recent call last):
  File "/home/shashank/.local/bin/py7zr", line 11, in <module>
    sys.exit(main())
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/__main__.py", line 25, in main
    return cli.Cli().run()
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/cli.py", line 91, in run
    return args.func(args)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/cli.py", line 297, in run_extract
    a.extractall(callback=cb)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 629, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 735, in _extract
    self.worker.extract(self.fp, parallel=(not self.password_protected and not self._filePassed))
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 954, in extract
    self.extract_single(fp, self.files, self.src_start, src_end, q)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 1021, in extract_single
    raise e
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 1005, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 1058, in decompress
    tmp = decompressor.decompress(inp, max_length)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/compressor.py", line 763, in decompress
    folder_data = self.cchain.decompress(data, max_length=max_length)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/compressor.py", line 687, in decompress
    tmp = self._decompress(data, max_length)
  File "/home/shashank/.local/lib/python3.6/site-packages/py7zr/compressor.py", line 663, in _decompress
    data = decompressor.decompress(data)
_lzma.LZMAError: Corrupt input data
`

**Comment by robustTechie** [comment]
Please help me to fix this.

**Comment by miurahr** [comment]
@robustTechie It seems different issue than this one.

**Comment by robustTechie** [comment]
Can you help me in fixing this

**Comment by miurahr** [comment]
@robustTechie Could you open a new issue for that?

**Pull request merged**
