### PR TITLE
Fix/hidden files extraction

### PR DESCRIPTION
**Pull request by DoNck**
Hello,

I am creating this issue because I found a change that is likely not intended.

I made some modifications to address this issue in the enclosed PR.

Thank you for your time and effort.

# Describe the bug
When extracted, hidden Linux files and folders are renamed and become visible.

# To Reproduce
Please create an archive containing a folder starting with a dot (for example `.ssh`).

Then, write the following script:
```
from py7zr import SevenZipFile

with SevenZipFile("ssh_archive.7z", "r") as archive_handle:
    archive_handle.extractall()
# end with
```
Finally, execute it, the `.ssh` will be extracted as `ssh`

# Expected behavior
Files and folders should remain as-is when extracted

# Environment (please complete the following information):
* OS: Ubuntu 18 - 64 bits, 4Gb of RAM
* Python 3.8.5
* py7zr version: 0.18.6, installed via pip

# Test data(please attach in the report):
Please refer to the test archives in the enclosed PR

# Additional context
In general, files and folders starting with `.` or `\` would be renamed.

This is caused by the use of `lstrip("./")` which is matching on every character and not the combination of them.

This is effective in the current version (18.6), but wasn't in previous ones (tested on 16.1).

### CODE REVIEW

**Comment by miurahr** [comment]
``tox check`` failed because of PEP8. Could you run ``black tests`` to format it? @DoNck

**Comment by DoNck** [comment]
Sorry about that, I ran black to fix the formatting issues, as requested

**Comment by miurahr** [comment]
@DoNck it is very good catch and looks good for the fix.
Thank you for the proposal.

**Comment by miurahr** [comment]
v0.18.7 is out with the fix.

**Pull request merged**
