### PR TITLE
[WIP] Give deflate64 compression capability via codecs7z

### PR DESCRIPTION
**Pull request by cielavenir**

### CODE REVIEW

**Comment by cielavenir** [comment]
the thing is, windows is not supported

**Comment by cielavenir** [comment]
now windows is supported. as switching submodule hash is required, source installation is not supported and I need to publish binary wheel. I integrated zipfile_deflate64's yaml.

**Comment by miurahr** [comment]
I don't want to support write of deflate64 because it is still proprietary algorithm and inefficient. There is no reason to create new archive with deflate64 instead of zstandard or lzma2. Decompression is ok for backward compatibility, help persons who already have archives with deflate64.

**Comment by cielavenir** [comment]
set to WIP until https://github.com/brianhelba/zipfile-deflate64/issues/28 is settled

**Comment by miurahr** [comment]
Recent version of 7zip (7-zip.org) does not provide an option to compress data with deflate64/7z. Only for deflate64/zip.
It is because, I don't want to support a deflate64 compression  on py7zr.

**Comment by cielavenir** [comment]
I don't (partly) understand, tried `7zz a -t7z -mm=deflate64 a.7z` with stock 7-zip 22.00 and it worked normally.

**Pull request closed without merging**
